image: node:latest

stages:
    - mirror
    - gitlab-pages
    - github-pages
    - docker-build

mirror:
    stage: mirror
    script:
        #github
        - USERNAME=pektin-dolly
        - git config --global user.email "runner@${CI_SERVER_HOST}"
        - git config --global user.name "runner"
        - git fetch --unshallow origin || true
        - git remote remove origin
        - git remote add origin https://${USERNAME}:${GITHUB_TOKEN}@github.com/pektin-dns/${CI_PROJECT_NAME}.git
        - echo " " >> .gitlab-ci.yml
        - git add -A
        - git commit -m "🐑 mirror [skip ci]"
        - curl -u "${USERNAME}:${GITHUB_TOKEN}" https://api.github.com/user/repos -d "{\"name\":\"${CI_PROJECT_NAME}\"}"
        - curl --request PATCH -u "${USERNAME}:${GITHUB_TOKEN}" https://api.github.com/repos/pektin-dns/${CI_PROJECT_NAME} -d "{\"description\":\"This is a mirror of ${CI_PROJECT_URL}\"}"
        - git push --set-upstream origin HEAD:refs/heads/main -f || true
        #gitlab
        - git remote remove origin
        - git remote add origin https://${USERNAME}:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
        - git push --set-upstream origin HEAD:refs/heads/main -f

github-pages:
    stage: github-pages
    script:
        - MAIN_URL=https://pektin.y.gy.
        - URL=https://pektin-dns.github.io/
        - USERNAME=pektin-dolly
        - git config --global user.email "runner@${CI_SERVER_HOST}"
        - git config --global user.name "runner"
        - sed -i "s|$MAIN_URL|$URL|g" ./docusaurus.config.js
        - yarn
        - yarn build
        - sed -i -e "s|<head>|<head>$(cat deployment/csp.html | sed 's|"|\x22|g' | sed "s|'|\\\x27|g" | tr -d '\n')|g" ./build/index.html
        - cat deployment/README_GITHUB.md > build/README.md
        - cp -r build/ /
        - cd /build/
        - git init
        - git add -A
        - git commit -m "🐑 build docs"
        - git remote add origin https://${USERNAME}:${GITHUB_TOKEN}@github.com/pektin-dns/docs.git
        - git push --set-upstream origin HEAD:refs/heads/main -f || true

gitlab-pages:
    stage: gitlab-pages
    script:
        - MAIN_URL=https://pektin.y.gy.
        - URL=https://pektin-dns.github.io/
        - USERNAME=pektin-dolly
        - git config --global user.email "runner@${CI_SERVER_HOST}"
        - git config --global user.name "runner"
        - sed -i "s|$MAIN_URL|$URL|g" ./docusaurus.config.js
        - yarn
        - yarn build
        - sed -i -e "s|<head>|<head>$(cat deployment/csp.html | sed 's|"|\x22|g' | sed "s|'|\\\x27|g" | tr -d '\n')|g" ./build/index.html
        - cat deployment/README_GITLAB.md > build/README.md
        - cat deployment/.gitlab.com-ci.yml > build/.gitlab-ci.yml
        - cp -r build/ /
        - cd /build/
        - git init
        - git add -A
        - git commit -m "🐑 build docs"
        - git remote add origin https://${USERNAME}:${GITLAB_TOKEN}@gitlab.com/pektin/docs.git
        - git push --set-upstream origin HEAD:refs/heads/main -f || true

docker-build:
    stage: docker-build
    image: docker:latest
    before_script:
        - docker login -u "pektin" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker build --pull -t "pektin/docs" .
        - docker push "pektin/docs"

